import Role from './Role';
import Team from './Team';

const ship = new Map<Role, Team>();

ship.set(Role.Unknown, Team.Unknown);
ship.set(Role.Werewolf, Team.Werewolf);
ship.set(Role.Villager, Team.Villager);
ship.set(Role.Seer, Team.Villager);
ship.set(Role.Tanner, Team.Other);
ship.set(Role.Minion, Team.Werewolf);
ship.set(Role.Troublemaker, Team.Villager);
ship.set(Role.Robber, Team.Villager);
ship.set(Role.Drunk, Team.Villager);
ship.set(Role.Mason, Team.Villager);
ship.set(Role.Hunter, Team.Villager);
ship.set(Role.Witch, Team.Villager);
ship.set(Role.AlphaWolf, Team.Werewolf);
ship.set(Role.DreamWolf, Team.Werewolf);
ship.set(Role.Prince, Team.Villager);
ship.set(Role.MysticWolf, Team.Werewolf);
ship.set(Role.Cursed, Team.Villager);
ship.set(Role.ParanormalInvestigator, Team.Villager);
ship.set(Role.Insomniac, Team.Villager);
ship.set(Role.Doppelganger, Team.Other);
ship.set(Role.Sentinel, Team.Villager);
ship.set(Role.ApprenticeSeer, Team.Villager);
ship.set(Role.VillageIdiot, Team.Villager);
ship.set(Role.Revealer, Team.Villager);
ship.set(Role.Curator, Team.Villager);
ship.set(Role.Bodyguard, Team.Villager);
ship.set(Role.AuraSeer, Team.Villager);
ship.set(Role.ApprenticeTanner, Team.Other);
ship.set(Role.Beholder, Team.Villager);
ship.set(Role.Thing, Team.Villager);
ship.set(Role.Squire, Team.Werewolf);
ship.set(Role.Renfield, Team.Vampire);
ship.set(Role.TheCount, Team.Vampire);
ship.set(Role.TheMaster, Team.Vampire);
ship.set(Role.Vampire, Team.Vampire);
ship.set(Role.Cupid, Team.Villager);
ship.set(Role.Diseased, Team.Villager);
ship.set(Role.Gremlin, Team.Villager);
ship.set(Role.Instigator, Team.Villager);
ship.set(Role.Marksman, Team.Villager);
ship.set(Role.Pickpocket, Team.Villager);
ship.set(Role.Priest, Team.Villager);
ship.set(Role.ApprenticeAssassin, Team.Other);
ship.set(Role.Assassin, Team.Other);
ship.set(Role.Copycat, Team.Other);

export default ship;
